name: Build docker image

on:
    push:
        branches:
            - master

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Get Short SHA
              id: vars
              run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

          #  - name: Change Tag to last image
           #   run: |
            #    docker pull san43zko/server-utility-backend:latest
             #   docker tag san43zko/server-utility-backend:latest san43zko/server-utility-backend:${{ steps.vars.outputs.sha_short }}-$(date +'%Y-%m-%d')
              #  docker push san43zko/server-utility-backend:${{ steps.vars.outputs.sha_short }}-$(date +'%Y-%m-%d')

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v6
              with:
                file: ./Dockerfile
                push: true
                tags: san43zko/server-utility-backend:latest
